---
title: "Impact of Airbnb on Seattle's Neighborhoods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> Jill Nguyen, Pooja Ramanathan, Shiva Rithwick, Victoria Huynh

## Introduction
As home-sharing rental sites become more popular, the housing market of urban areas change more and more. Gentrification is a rising problem in many American cities today. While gentrification is usually attributed to an influx of new affluent residents into a neighborhood, the purchase of properties in a neighborhood solely to house short-term visitors may also be an overlooked factor. Using this resource, we want to answer **QUESTION HERE**.  
In this resource, we will specifically look at Airbnb's impact on Seattle's neighborhoods{, starting from 2011}.  

## Our Dataset
The dataset we are using is provided by [Inside Airbnb](http://insideairbnb.com/get-the-data.html) (2019). It includes information about Airbnb listings in Seattle. It has been cleaned to remove columns not relevant to our research. {We also added X new columns: `x`, `x`, and `x`. (add if true)}  
Below is a sample of our dataset.  
{DATASET HEAD}  
{WHAT EACH COLUMN REPRESENTS BUT MAYBE NOT BC THERE ARE 65}

## Data Exploration
We did a further exploration on our dataset to familiarize ourselves with its variables.

First, we wanted to see how Airbnb listings were distributed in Seattle.  
{VIZ}  
We noticed that {DISCOVERY}.

We then sought to see whether there was a relationship between the housing price hikes in neighborhoods and the Airbnb listings of Seattle. In order to do this, we researched and found out {PRICE HIKE INFO}. [cite]()  
{VIZ}  
We discovered that {DISCOVERY}.

Our most significant findings told us {FINDINGS}.

## Modeling
We used {MODEL} model to predict whether or not a listing was used for personal{FIX WORDING?} or commercial purposes.  
{INFO ABOUT MODEL}